import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';

/**
 * Emits a service worker that precaches every built asset, so the game is fully
 * playable offline after one visit. The file list comes from the bundle itself,
 * which is why this is a plugin rather than a static file: hashed asset names
 * change on every build and a stale list would silently break offline play.
 */
const serviceWorkerPlugin = (): Plugin => ({
  name: 'codequest-service-worker',
  apply: 'build',
  generateBundle(_options, bundle) {
    // '/' and '/index.html' are the same document but are matched separately,
    // so the navigation fallback needs both.
    const precache = [...new Set(['/', '/index.html', ...Object.keys(bundle).map((file) => `/${file}`)])];
    const version = createHash('sha256').update(precache.join('|')).digest('hex').slice(0, 12);
    this.emitFile({
      type: 'asset',
      fileName: 'sw.js',
      source: `// Generated by vite.config.ts. Do not edit.
const CACHE = 'codequest-${version}';
const PRECACHE = ${JSON.stringify(precache)};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)));
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names.filter((name) => name !== CACHE).map((name) => caches.delete(name)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  if (new URL(request.url).origin !== self.location.origin) return;

  event.respondWith((async () => {
    const cached = await caches.match(request, { ignoreSearch: true });
    if (cached) return cached;
    try {
      const response = await fetch(request);
      if (response.ok) {
        const cache = await caches.open(CACHE);
        await cache.put(request, response.clone());
      }
      return response;
    } catch (error) {
      if (request.mode === 'navigate') {
        const shell = await caches.match('/index.html');
        if (shell) return shell;
      }
      throw error;
    }
  })());
});

// The page decides when an update takes effect; see src/serviceWorker.ts.
self.addEventListener('message', (event) => {
  if (event.data === 'skipWaiting') self.skipWaiting();
});
`,
    });
  },
});

export default defineConfig({
  plugins: [react(), serviceWorkerPlugin()],
  resolve: {
    dedupe: ['react', 'react-dom', 'three'],
    alias: [
      {
        find: '@codequest/code-runner/worker',
        replacement: fileURLToPath(new URL('../../packages/code-runner/src/worker.ts', import.meta.url)),
      },
      { find: '@codequest/domain', replacement: fileURLToPath(new URL('../../packages/domain/src/index.ts', import.meta.url)) },
      { find: '@codequest/simulation', replacement: fileURLToPath(new URL('../../packages/simulation/src/index.ts', import.meta.url)) },
      { find: '@codequest/content', replacement: fileURLToPath(new URL('../../packages/content/src/index.ts', import.meta.url)) },
      { find: '@codequest/code-runner', replacement: fileURLToPath(new URL('../../packages/code-runner/src/index.ts', import.meta.url)) },
      { find: '@codequest/persistence', replacement: fileURLToPath(new URL('../../packages/persistence/src/index.ts', import.meta.url)) },
      { find: '@codequest/renderer', replacement: fileURLToPath(new URL('../../packages/renderer/src/index.ts', import.meta.url)) },
      { find: '@codequest/editor', replacement: fileURLToPath(new URL('../../packages/editor/src/index.ts', import.meta.url)) },
      { find: '@codequest/ui', replacement: fileURLToPath(new URL('../../packages/ui/src/index.ts', import.meta.url)) },
    ],
  },
  worker: {
    format: 'es',
  },
  optimizeDeps: {
    exclude: ['@jitl/quickjs-wasmfile-release-sync'],
  },
  build: {
    rollupOptions: {
      output: {
        manualChunks(id) {
          if (id.includes('@codemirror') || id.includes('/codemirror/')) return 'editor-runtime';
          if (id.includes('@react-three') || id.includes('/three/')) return 'scene-runtime';
        },
      },
    },
  },
});
