import type { MissionPackageSchema } from '@codequest/domain';

export const m01FirstSteps: MissionPackageSchema = {
  identity: {
    levelId: 'm01',
    zoneId: 'meadow-of-moves',
    apiVersion: 'v1',
    contentVersion: '2025.01',
    ordinal: 1,
    title: 'First Steps',
    isCheckpoint: false,
    prerequisiteLevelIds: [],
  },
  zoneId: 'meadow-of-moves',
  curriculum: {
    primaryConcept: 'sequence',
    newConcepts: ['moveForward'],
    priorConcepts: [],
    transferPrompt: 'What is the very first command a brand-new runner needs?',
  },
  startState: {
    avatar: { cellX: 0, cellZ: 0, facing: 'east' },
    collected: [],
    inventory: {},
    flags: {},
    stepCount: 0,
  },
  objects: [
    {
      id: 'spawn-1',
      label: 'Trailhead',
      required: false,
      kind: 'spawn',
      cell: { cellX: 0, cellZ: 0 },
      facing: 'east',
    },
    {
      id: 'goal-1',
      label: 'Beacon',
      required: true,
      kind: 'goal',
      cell: { cellX: 3, cellZ: 0 },
      successConditions: ['avatarAtGoal'],
    },
    {
      id: 'decor-grass-1',
      label: 'Tuft of grass',
      required: false,
      kind: 'decor',
      cells: [{ cellX: 1, cellZ: -1 }],
      assetId: 'asset.grass.tuft',
      interactive: false,
    },
  ],
  allowedApi: [
    {
      capabilityId: 'cap-move-forward',
      unlockedFromMissionId: 'm01',
      apiVersion: 'v1',
    },
  ],
  briefing: {
    storySentence: 'A friendly avatar waits at the trailhead. Walk three cells east to reach the beacon.',
    goal: 'Reach the beacon.',
    requiredCount: 1,
    optionalCount: 0,
    newConcepts: ['moveForward'],
    priorConcepts: [],
    controls: ['move forward', 'turn left', 'turn right'],
    checklist: ['Press Run when you are ready.'],
    readAloud: 'Walk three steps east to reach the beacon.',
    locale: 'en-US',
  },
  starterCode: 'moveForward();\n',
  hints: [
    {
      hintId: 'h1',
      stage: 1,
      prompt: 'Tap Run and watch what happens.',
      reveal: 'One moveForward step moves one cell east.',
    },
    {
      hintId: 'h2',
      stage: 2,
      prompt: 'You need three moveForward() calls in a row.',
      scaffold: 'moveForward();',
    },
    {
      hintId: 'h3',
      stage: 3,
      prompt: 'Write three moveForward() lines, then Run.',
      scaffold: 'moveForward();\nmoveForward();\nmoveForward();',
    },
    {
      hintId: 'h4',
      stage: 4,
      prompt: 'Solution shown below.',
      reveal: 'moveForward();\nmoveForward();\nmoveForward();',
    },
  ],
  analogousExample: {
    title: 'Walking the short hall',
    problem: 'Reach the end of a three-cell hallway.',
    source: 'examples/hallway-three-cells',
    note: 'Pair this with the trailhead story to anchor the moveForward() concept.',
  },
  completion: {
    stateInvariants: ['avatarAt(3,0)', 'stepCount >= 3'],
    requiredObjectIds: ['goal-1'],
    requiredFlags: {},
    requiredCollected: [],
    terminalCell: { cellX: 3, cellZ: 0 },
    reflectionQuestion: 'What changes if you add a turnLeft() before the first moveForward()?',
  },
  conceptEvidence: [
    {
      ruleKey: 'rule.sequence',
      expectedSequence: ['moveForward', 'moveForward', 'moveForward'],
    },
    {
      ruleKey: 'rule.moveUsed',
      kind: 'functionCalledWithArgs',
      threshold: 3,
    },
  ],
  knownSolutions: [
    {
      solutionId: 'sol-m01-straight',
      source: 'demo/m01-straight.js',
      expectedCommandCount: 3,
      expectedStepCount: 3,
      notes: 'Three east moveForward() calls; canonical solution.',
    },
    {
      solutionId: 'sol-m01-fan',
      source: 'demo/m01-fan.js',
      expectedCommandCount: 7,
      expectedStepCount: 3,
      notes: 'Adds a loop-free turn-and-recover pattern; reaches the same goal cell.',
    },
  ],
  expectedFailures: [
    {
      fixtureId: 'fixture-m01-too-few',
      source: 'tests/m01/too-few.js',
      expectedFault: 'emptyCollect',
      reasonKey: 'goal-not-reached',
      notes: 'Starter code has one moveForward(); never reaches beacon.',
    },
    {
      fixtureId: 'fixture-m01-wrong-facing',
      source: 'tests/m01/wrong-facing.js',
      expectedFault: 'wrongFacing',
      reasonKey: 'avatar-facing-mismatch',
      notes: 'Turning right instead of forward leads off the trail.',
    },
    {
      fixtureId: 'fixture-m01-runaway-loop',
      source: 'tests/m01/runaway-loop.js',
      expectedFault: 'runawayLoop',
      reasonKey: 'budget-exceeded',
      notes: 'A while(true) loop blows the command budget guard.',
    },
  ],
  accessibility: {
    keyboard: 'ArrowRight moves forward; ArrowLeft/ArrowRight when stopped turn.',
    touch: 'Tap and hold the move-forward button to repeat.',
    captions: 'Caption strip shows the last applied command and result reason.',
    textScale: 'Honors app textScale setting; briefing stays at 16px minimum.',
    reducedMotion: 'Beacon pulse and dust particles disabled under reduced motion.',
    screenReader: 'Each tile action announced with cell coordinates; goals read as "Beacon reached".',
  },
  budgets: {
    maxCommands: 6,
    maxStepCount: 12,
    maxMissionObjects: 6,
    maxTriangles: 8000,
    estimatedActiveMinutes: 3,
  },
  rewards: [
    {
      rewardId: 'reward-first-step',
      assetId: 'asset.badge.first-step',
      label: 'First Step',
      cosmetic: true,
    },
  ],
};
