import type { MissionPackageSchema } from '@codequest/domain';

/**
 * M13 repeated one command; this repeats two, which is the first time the loop
 * body has to be read as a unit. Three buoy lamps sit one cell apart along the
 * channel, so every pass is step-then-light and a move-only loop leaves the
 * lamps dark in a way the child can see from the boat.
 */
export const m14LightTheBuoys: MissionPackageSchema = {
  identity: {
    levelId: 'm14',
    zoneId: 'loop-lagoon',
    apiVersion: 'v1',
    contentVersion: '2025.01',
    ordinal: 2,
    title: 'Light the Buoys',
    isCheckpoint: false,
    prerequisiteLevelIds: ['m13'],
  },
  zoneId: 'loop-lagoon',
  curriculum: {
    primaryConcept: 'countingLoop',
    newConcepts: ['loopBody'],
    priorConcepts: ['forLoop', 'moveForward', 'interact'],
    transferPrompt: 'When two things happen every time, where do both of them belong?',
  },
  startState: {
    avatar: { cellX: 0, cellZ: 0, facing: 'east' },
    collected: [],
    inventory: {},
    flags: {},
    stepCount: 0,
  },
  objects: [
    {
      id: 'spawn-1',
      label: 'Channel mouth',
      required: false,
      kind: 'spawn',
      cell: { cellX: 0, cellZ: 0 },
      facing: 'east',
    },
    {
      id: 'channel-water',
      label: 'Deep water',
      required: false,
      kind: 'blocker',
      occupiedCells: [
        { cellX: 1, cellZ: -1 },
        { cellX: 2, cellZ: -1 },
        { cellX: 3, cellZ: -1 },
        { cellX: 4, cellZ: -1 },
        { cellX: 5, cellZ: -1 },
        { cellX: 6, cellZ: -1 },
        { cellX: 1, cellZ: 1 },
        { cellX: 2, cellZ: 1 },
        { cellX: 3, cellZ: 1 },
        { cellX: 4, cellZ: 1 },
        { cellX: 5, cellZ: 1 },
        { cellX: 6, cellZ: 1 },
        { cellX: 6, cellZ: 0 },
      ],
      reasonKey: 'water.blocks',
    },
    {
      id: 'buoy-1',
      label: 'First buoy lamp',
      required: true,
      kind: 'interactable',
      cell: { cellX: 2, cellZ: 0 },
      actionKey: 'light',
      range: 1,
      initialState: 'dark',
      stateTransitions: [{ from: 'dark', to: 'lit' }],
    },
    {
      id: 'buoy-2',
      label: 'Second buoy lamp',
      required: true,
      kind: 'interactable',
      cell: { cellX: 3, cellZ: 0 },
      actionKey: 'light',
      range: 1,
      initialState: 'dark',
      stateTransitions: [{ from: 'dark', to: 'lit' }],
    },
    {
      id: 'buoy-3',
      label: 'Third buoy lamp',
      required: true,
      kind: 'interactable',
      cell: { cellX: 4, cellZ: 0 },
      actionKey: 'light',
      range: 1,
      initialState: 'dark',
      stateTransitions: [{ from: 'dark', to: 'lit' }],
    },
    {
      id: 'goal-1',
      label: 'Boat dock',
      required: true,
      kind: 'goal',
      cell: { cellX: 5, cellZ: 0 },
      successConditions: ['avatarAtGoal'],
    },
  ],
  allowedApi: [
    { capabilityId: 'cap-move-forward', unlockedFromMissionId: 'm01', apiVersion: 'v1' },
    { capabilityId: 'cap-interact', unlockedFromMissionId: 'm04', apiVersion: 'v1' },
  ],
  briefing: {
    storySentence: 'Three buoy lamps are dark. Light each one as you walk the channel.',
    goal: 'Light all three buoy lamps, then reach the dock.',
    requiredCount: 3,
    optionalCount: 0,
    newConcepts: ['loopBody'],
    priorConcepts: ['forLoop', 'moveForward', 'interact'],
    controls: ['move forward', 'interact'],
    checklist: ['Step once, then light the lamp.', 'Do that three times in a loop.', 'Walk on to the dock.'],
    readAloud: 'Step, then light. Do that three times. Then walk to the dock.',
    locale: 'en-US',
  },
  starterCode: '// Each lamp needs a step and a light.\nfor (let i = 0; i < 3; i++) {\n  moveForward();\n}\n',
  hints: [
    {
      hintId: 'h1',
      stage: 1,
      prompt: 'Run the starter code. The lamps stay dark. What is missing?',
      reveal: 'The loop only steps. Lighting a lamp has to happen inside it too.',
    },
    {
      hintId: 'h2',
      stage: 2,
      prompt: 'Put both lines inside the braces, in the order you do them.',
      scaffold: 'for (let i = 0; i < 3; i++) {\n  moveForward();\n  interact();\n}',
    },
    {
      hintId: 'h3',
      stage: 3,
      prompt: 'The dock is two cells past the last lamp. Add those steps after the loop.',
      scaffold: 'for (let i = 0; i < 3; i++) {\n  moveForward();\n  interact();\n}\nmoveForward();\nmoveForward();',
    },
    {
      hintId: 'h4',
      stage: 4,
      prompt: 'Here is the answer.',
      reveal:
        'for (let i = 0; i < 3; i++) {\n  moveForward();\n  interact();\n}\n\nmoveForward();\nmoveForward();',
    },
  ],
  analogousExample: {
    title: 'Beds in the morning',
    problem: 'In each room you open the blind and turn off the lamp. Then you go on.',
    source: 'examples/beds-in-the-morning',
    note: 'Both jobs happen in every room, so both belong in the repeated part.',
  },
  completion: {
    stateInvariants: ['avatarAtGoal'],
    requiredObjectIds: ['goal-1', 'buoy-1', 'buoy-2', 'buoy-3'],
    requiredFlags: {
      'interactable.buoy-1.state': true,
      'interactable.buoy-2.state': true,
      'interactable.buoy-3.state': true,
    },
    requiredCollected: [],
    terminalCell: { cellX: 5, cellZ: 0 },
    reflectionQuestion: 'What two things happened in each turn of your loop?',
  },
  conceptEvidence: [
    {
      ruleKey: 'rule.sequence',
      expectedSequence: ['moveForward', 'interact', 'moveForward', 'interact', 'moveForward', 'interact'],
    },
    { ruleKey: 'rule.forLoop', kind: 'forLoop', threshold: 1 },
  ],
  knownSolutions: [
    {
      solutionId: 'sol-m14-two-line-body',
      source: 'demo/m14-two-line-body.js',
      expectedCommandCount: 8,
      expectedStepCount: 8,
      notes: 'Loop of move plus interact three times, then two steps to the dock.',
    },
    {
      solutionId: 'sol-m14-helper-then-loop',
      source: 'demo/m14-helper-then-loop.js',
      expectedCommandCount: 8,
      expectedStepCount: 8,
      notes: 'Same route with the body wrapped in a lightNext() helper, reusing the M09 idea.',
    },
  ],
  expectedFailures: [
    {
      fixtureId: 'fixture-m14-move-only',
      source: 'tests/m14/move-only.js',
      expectedFault: 'closedGate',
      reasonKey: 'goal-not-reached',
      notes: 'Starter code walks the channel with every lamp still dark.',
    },
    {
      fixtureId: 'fixture-m14-interact-only',
      source: 'tests/m14/interact-only.js',
      expectedFault: 'outOfRange',
      reasonKey: 'interact.nothing-here',
      notes: 'Loop interacts without stepping, so no lamp is ever in front of the boat.',
    },
    {
      fixtureId: 'fixture-m14-early-stop',
      source: 'tests/m14/early-stop.js',
      expectedFault: 'closedGate',
      reasonKey: 'goal-not-reached',
      notes: 'Loop runs twice, so the third lamp is never lit.',
    },
  ],
  accessibility: {
    keyboard: 'Arrow keys move; Enter interacts; Step mode advances one loop pass at a time.',
    touch: 'Action buttons keep the M06 order so muscle memory carries into the lagoon.',
    captions: 'Caption strip names the lamp lit on each pass and how many are left.',
    textScale: 'Honors app textScale setting; briefing stays at 16px minimum.',
    reducedMotion: 'Lamp flare and the completed-pass ring appear instantly under reduced motion.',
    screenReader: 'Each lit lamp is announced once with its pass number.',
  },
  budgets: {
    maxCommands: 14,
    maxStepCount: 16,
    maxMissionObjects: 8,
    maxTriangles: 8000,
    estimatedActiveMinutes: 7,
  },
  rewards: [
    { rewardId: 'reward-buoy-glow', assetId: 'asset.cosmetic.buoy-glow-trail', label: 'Buoy Glow Trail', cosmetic: true },
  ],
};
