import type { MissionPackageSchema } from '@codequest/domain';

/**
 * The first loop whose body changes the facing, which is where children stop
 * seeing a loop as "do this n times" and start seeing it as "one side of a
 * square". Four mooring posts sit off the dock, one per side, so the four
 * required flags can only be set by walking the whole perimeter in order.
 * The pearl waits in the middle, reachable only after the circuit closes.
 */
export const m15SquareDock: MissionPackageSchema = {
  identity: {
    levelId: 'm15',
    zoneId: 'loop-lagoon',
    apiVersion: 'v1',
    contentVersion: '2025.01',
    ordinal: 3,
    title: 'Square Dock',
    isCheckpoint: false,
    prerequisiteLevelIds: ['m14'],
  },
  zoneId: 'loop-lagoon',
  curriculum: {
    primaryConcept: 'countingLoop',
    newConcepts: ['loopWithTurn'],
    priorConcepts: ['forLoop', 'loopBody', 'moveForward', 'turnRight', 'interact', 'collect'],
    transferPrompt: 'What has to happen at the end of every side for the route to close?',
  },
  startState: {
    avatar: { cellX: 0, cellZ: 0, facing: 'east' },
    collected: [],
    inventory: {},
    flags: {},
    stepCount: 0,
  },
  objects: [
    {
      id: 'spawn-1',
      label: 'Dock gate',
      required: false,
      kind: 'spawn',
      cell: { cellX: 0, cellZ: 0 },
      facing: 'east',
    },
    {
      id: 'post-east',
      label: 'East mooring post',
      required: true,
      kind: 'interactable',
      cell: { cellX: 3, cellZ: 0 },
      actionKey: 'tie',
      range: 1,
      initialState: 'loose',
      stateTransitions: [{ from: 'loose', to: 'tied' }],
    },
    {
      id: 'post-south',
      label: 'South mooring post',
      required: true,
      kind: 'interactable',
      cell: { cellX: 2, cellZ: 3 },
      actionKey: 'tie',
      range: 1,
      initialState: 'loose',
      stateTransitions: [{ from: 'loose', to: 'tied' }],
    },
    {
      id: 'post-west',
      label: 'West mooring post',
      required: true,
      kind: 'interactable',
      cell: { cellX: -1, cellZ: 2 },
      actionKey: 'tie',
      range: 1,
      initialState: 'loose',
      stateTransitions: [{ from: 'loose', to: 'tied' }],
    },
    {
      id: 'post-north',
      label: 'North mooring post',
      required: true,
      kind: 'interactable',
      cell: { cellX: 0, cellZ: -1 },
      actionKey: 'tie',
      range: 1,
      initialState: 'loose',
      stateTransitions: [{ from: 'loose', to: 'tied' }],
    },
    {
      id: 'lagoon-water',
      label: 'Open water',
      required: false,
      kind: 'blocker',
      occupiedCells: [
        { cellX: -1, cellZ: -1 },
        { cellX: 0, cellZ: -1 },
        { cellX: 1, cellZ: -1 },
        { cellX: 2, cellZ: -1 },
        { cellX: 3, cellZ: -1 },
        { cellX: -1, cellZ: 0 },
        { cellX: 3, cellZ: 0 },
        { cellX: -1, cellZ: 1 },
        { cellX: 3, cellZ: 1 },
        { cellX: -1, cellZ: 2 },
        { cellX: 3, cellZ: 2 },
        { cellX: -1, cellZ: 3 },
        { cellX: 0, cellZ: 3 },
        { cellX: 1, cellZ: 3 },
        { cellX: 2, cellZ: 3 },
        { cellX: 3, cellZ: 3 },
      ],
      reasonKey: 'water.blocks',
    },
    {
      id: 'pearl-1',
      label: 'Dock pearl',
      required: true,
      kind: 'collectible',
      cell: { cellX: 1, cellZ: 1 },
      collectionEffect: 'pearl',
    },
    {
      id: 'goal-1',
      label: 'Middle of the dock',
      required: true,
      kind: 'goal',
      cell: { cellX: 1, cellZ: 1 },
      successConditions: ['avatarAtGoal'],
    },
  ],
  allowedApi: [
    { capabilityId: 'cap-everything', unlockedFromMissionId: 'm06', apiVersion: 'v1' },
  ],
  briefing: {
    storySentence: 'The dock is a square. Each side ends at a rope post that needs a tie.',
    goal: 'Tie all four posts, then get the pearl in the middle.',
    requiredCount: 5,
    optionalCount: 0,
    newConcepts: ['loopWithTurn'],
    priorConcepts: ['forLoop', 'moveForward', 'turnRight', 'interact', 'collect'],
    controls: ['move forward', 'turn left', 'turn right', 'collect', 'interact'],
    checklist: ['Walk one side of the dock.', 'Tie the post at the end.', 'Turn right.', 'Do it four times, then get the pearl.'],
    readAloud: 'Walk two steps, tie the post, turn right. Do that four times.',
    locale: 'en-US',
  },
  starterCode: '// Walk one side by hand first. What did you do at the end of it?\nmoveForward();\nmoveForward();\ninteract();\n',
  hints: [
    {
      hintId: 'h1',
      stage: 1,
      prompt: 'Walk one side in your head. Say each thing you did, in order.',
      reveal: 'One side is the same four things: step, step, tie, turn.',
    },
    {
      hintId: 'h2',
      stage: 2,
      prompt: 'Put all four of those in the loop body. The turn goes last.',
      scaffold: 'for (let i = 0; i < 4; i++) {\n  moveForward();\n  moveForward();\n  interact();\n  turnRight();\n}',
    },
    {
      hintId: 'h3',
      stage: 3,
      prompt: 'The loop ends where it started. The pearl is one step in and one step down.',
      scaffold: 'moveForward();\nturnRight();\nmoveForward();',
    },
    {
      hintId: 'h4',
      stage: 4,
      prompt: 'Here is the answer.',
      reveal:
        'for (let i = 0; i < 4; i++) {\n  moveForward();\n  moveForward();\n  interact();\n  turnRight();\n}\n\nmoveForward();\nturnRight();\nmoveForward();\ncollect();',
    },
  ],
  analogousExample: {
    title: 'Around the yard',
    problem: 'You walk around a square yard. At each corner you turn the same way.',
    source: 'examples/around-the-yard',
    note: 'The turn is part of the side, not something extra you remember at the end.',
  },
  completion: {
    stateInvariants: ['avatarAtGoal'],
    requiredObjectIds: ['goal-1', 'pearl-1', 'post-east', 'post-south', 'post-west', 'post-north'],
    requiredFlags: {
      'interactable.post-east.state': true,
      'interactable.post-south.state': true,
      'interactable.post-west.state': true,
      'interactable.post-north.state': true,
    },
    requiredCollected: ['pearl-1'],
    terminalCell: { cellX: 1, cellZ: 1 },
    reflectionQuestion: 'What did you do at the end of every side?',
  },
  conceptEvidence: [
    {
      ruleKey: 'rule.sequence',
      expectedSequence: ['moveForward', 'moveForward', 'interact', 'turnRight'],
    },
    { ruleKey: 'rule.forLoop', kind: 'forLoop', threshold: 1 },
  ],
  knownSolutions: [
    {
      solutionId: 'sol-m15-four-sides',
      source: 'demo/m15-four-sides.js',
      expectedCommandCount: 20,
      expectedStepCount: 20,
      notes: 'A loop of step, step, tie, turn four times, then three moves and a collect in the middle.',
    },
    {
      solutionId: 'sol-m15-helper-side',
      source: 'demo/m15-helper-side.js',
      expectedCommandCount: 20,
      expectedStepCount: 20,
      notes: 'Same route with the side wrapped in a walkSide() helper the loop calls four times.',
    },
  ],
  expectedFailures: [
    {
      fixtureId: 'fixture-m15-missing-turn',
      source: 'tests/m15/missing-turn.js',
      expectedFault: 'blockedMove',
      reasonKey: 'water.blocks',
      notes: 'Loop body has no turn, so the second pass walks straight off the east edge.',
    },
    {
      fixtureId: 'fixture-m15-three-sides',
      source: 'tests/m15/three-sides.js',
      expectedFault: 'closedGate',
      reasonKey: 'goal-not-reached',
      notes: 'Loop runs three times, so the north post is never tied.',
    },
    {
      fixtureId: 'fixture-m15-no-pearl',
      source: 'tests/m15/no-pearl.js',
      expectedFault: 'emptyCollect',
      reasonKey: 'goal-not-reached',
      notes: 'Circuit is complete but the run ends on the dock gate with no pearl.',
    },
  ],
  accessibility: {
    keyboard: 'Arrow keys move and turn; Enter ties a post; Space collects.',
    touch: 'Turn buttons stay separate from the move button, as in M05.',
    captions: 'Caption strip names the side just walked and the post just tied.',
    textScale: 'Honors app textScale setting; briefing stays at 16px minimum.',
    reducedMotion: 'Rope tie and water ripple are instant under reduced motion.',
    screenReader: 'The new compass direction is announced after every turn.',
  },
  budgets: {
    maxCommands: 26,
    maxStepCount: 26,
    maxMissionObjects: 10,
    maxTriangles: 9000,
    estimatedActiveMinutes: 9,
  },
  rewards: [
    { rewardId: 'reward-sailor-outfit', assetId: 'asset.cosmetic.sailor-outfit', label: 'Sailor Outfit', cosmetic: true },
  ],
};
