import type { MissionPackageSchema } from '@codequest/domain';

/**
 * Checkpoint: the tide wheel turns on five pegs spaced two cells apart, so one
 * pattern — step, step, push — repeats five times and nothing else will do.
 * The design brief asks for "five complete patterns" on a single wheel; the
 * simulation has no counter, only flags, so the five turns are five pegs and
 * the fifth peg is what opens the gate. Loops plus one prior function, the way
 * Echo Forest taught it, and the final walk out can be counted or sensed.
 */
export const m18LagoonCheckpoint: MissionPackageSchema = {
  identity: {
    levelId: 'm18',
    zoneId: 'loop-lagoon',
    apiVersion: 'v2',
    contentVersion: '2025.01',
    ordinal: 6,
    title: 'Lagoon Checkpoint',
    isCheckpoint: true,
    prerequisiteLevelIds: ['m17'],
  },
  zoneId: 'loop-lagoon',
  curriculum: {
    primaryConcept: 'countingLoop',
    newConcepts: [],
    priorConcepts: ['forLoop', 'whileLoop', 'loopBody', 'predicate', 'functionDeclaration', 'moveForward', 'interact'],
    transferPrompt: 'Which part of your code did you write once and run five times?',
  },
  startState: {
    avatar: { cellX: 0, cellZ: 0, facing: 'east' },
    collected: [],
    inventory: {},
    flags: {},
    stepCount: 0,
  },
  objects: [
    {
      id: 'spawn-1',
      label: 'Wheel walkway',
      required: false,
      kind: 'spawn',
      cell: { cellX: 0, cellZ: 0 },
      facing: 'east',
    },
    {
      id: 'peg-1',
      label: 'First wheel peg',
      required: true,
      kind: 'interactable',
      cell: { cellX: 3, cellZ: 0 },
      actionKey: 'push',
      range: 1,
      initialState: 'raised',
      stateTransitions: [{ from: 'raised', to: 'pushed' }],
    },
    {
      id: 'peg-2',
      label: 'Second wheel peg',
      required: true,
      kind: 'interactable',
      cell: { cellX: 5, cellZ: 0 },
      actionKey: 'push',
      range: 1,
      initialState: 'raised',
      stateTransitions: [{ from: 'raised', to: 'pushed' }],
    },
    {
      id: 'peg-3',
      label: 'Third wheel peg',
      required: true,
      kind: 'interactable',
      cell: { cellX: 7, cellZ: 0 },
      actionKey: 'push',
      range: 1,
      initialState: 'raised',
      stateTransitions: [{ from: 'raised', to: 'pushed' }],
    },
    {
      id: 'peg-4',
      label: 'Fourth wheel peg',
      required: true,
      kind: 'interactable',
      cell: { cellX: 9, cellZ: 0 },
      actionKey: 'push',
      range: 1,
      initialState: 'raised',
      stateTransitions: [{ from: 'raised', to: 'pushed' }],
    },
    {
      id: 'peg-5',
      label: 'Fifth wheel peg',
      required: true,
      kind: 'interactable',
      cell: { cellX: 11, cellZ: 0 },
      actionKey: 'push',
      range: 1,
      initialState: 'raised',
      stateTransitions: [{ from: 'raised', to: 'pushed' }],
    },
    {
      id: 'tide-gate',
      label: 'Tide gate',
      required: true,
      kind: 'blocker',
      occupiedCells: [{ cellX: 12, cellZ: 0 }],
      reasonKey: 'gate.closed',
      unlockedByFlag: 'interactable.peg-5.state',
    },
    {
      id: 'goal-1',
      label: 'Lagoon exit',
      required: true,
      kind: 'goal',
      cell: { cellX: 13, cellZ: 0 },
      successConditions: ['avatarAtGoal'],
    },
    {
      id: 'dock-end',
      label: 'End of the walkway',
      required: false,
      kind: 'blocker',
      occupiedCells: [{ cellX: 14, cellZ: 0 }],
      reasonKey: 'water.blocks',
    },
  ],
  allowedApi: [
    { capabilityId: 'cap-everything', unlockedFromMissionId: 'm06', apiVersion: 'v2' },
    { capabilityId: 'cap-sense-path', unlockedFromMissionId: 'm16', apiVersion: 'v2' },
  ],
  briefing: {
    storySentence: 'The tide wheel has five pegs. Each peg needs the same three moves.',
    goal: 'Push all five pegs, then walk out through the open gate.',
    requiredCount: 5,
    optionalCount: 0,
    newConcepts: [],
    priorConcepts: ['forLoop', 'whileLoop', 'functionDeclaration', 'moveForward', 'interact'],
    controls: ['move forward', 'turn left', 'turn right', 'collect', 'interact', 'check the way ahead'],
    checklist: ['Push one peg by hand first.', 'Make that push into a small plan.', 'Run the plan five times.', 'Walk out through the gate.'],
    readAloud: 'Two steps, then push. Do that five times. Then walk out the gate.',
    locale: 'en-US',
  },
  starterCode: '// Push one peg by hand. Then name what you did.\nfunction pushPeg() {\n  // Your three moves here.\n}\n\npushPeg();\n',
  hints: [
    {
      hintId: 'h1',
      stage: 1,
      prompt: 'Push the first peg by hand. Write down the moves you used.',
      reveal: 'It takes three moves every time: step, step, push.',
    },
    {
      hintId: 'h2',
      stage: 2,
      prompt: 'Give those three moves a name so you only write them once.',
      scaffold: 'function pushPeg() {\n  moveForward();\n  moveForward();\n  interact();\n}',
    },
    {
      hintId: 'h3',
      stage: 3,
      prompt: 'There are five pegs. Let a loop call your plan that many times.',
      scaffold: 'for (let i = 0; i < 5; i++) {\n  pushPeg();\n}',
    },
    {
      hintId: 'h4',
      stage: 4,
      prompt: 'Here is the answer.',
      reveal:
        'function pushPeg() {\n  moveForward();\n  moveForward();\n  interact();\n}\n\nfor (let i = 0; i < 5; i++) {\n  pushPeg();\n}\n\nwhile (canMoveForward()) {\n  moveForward();\n}',
    },
  ],
  analogousExample: {
    title: 'Winding a music box',
    problem: 'You wind a music box. Each turn of the key is the same small move.',
    source: 'examples/winding-a-music-box',
    note: 'Name one turn, then say how many turns. Nobody writes the turn five times.',
  },
  completion: {
    stateInvariants: ['avatarAtGoal'],
    requiredObjectIds: ['goal-1', 'peg-1', 'peg-2', 'peg-3', 'peg-4', 'peg-5'],
    requiredFlags: {
      'interactable.peg-1.state': true,
      'interactable.peg-2.state': true,
      'interactable.peg-3.state': true,
      'interactable.peg-4.state': true,
      'interactable.peg-5.state': true,
    },
    requiredCollected: [],
    terminalCell: { cellX: 13, cellZ: 0 },
    reflectionQuestion: 'Which part of your code did you write once and run five times?',
  },
  conceptEvidence: [
    {
      ruleKey: 'rule.sequence',
      expectedSequence: ['moveForward', 'moveForward', 'interact', 'moveForward', 'moveForward', 'interact'],
    },
    { ruleKey: 'rule.forLoop', kind: 'forLoop', threshold: 1 },
    { ruleKey: 'rule.functionDeclared', kind: 'functionDeclared', threshold: 1 },
  ],
  knownSolutions: [
    {
      solutionId: 'sol-m18-helper-in-loop',
      source: 'demo/m18-helper-in-loop.js',
      expectedCommandCount: 18,
      expectedStepCount: 18,
      notes: 'pushPeg() called five times by a for loop, then a while loop walks out to the exit.',
    },
    {
      solutionId: 'sol-m18-expanded',
      source: 'demo/m18-expanded.js',
      expectedCommandCount: 18,
      expectedStepCount: 18,
      notes: 'The same eighteen commands typed out in full; valid, and the recap compares the two.',
    },
  ],
  expectedFailures: [
    {
      fixtureId: 'fixture-m18-four-patterns',
      source: 'tests/m18/four-patterns.js',
      expectedFault: 'closedGate',
      reasonKey: 'gate.closed',
      notes: 'The loop runs four times, so the fifth peg is unpushed and the gate stays shut.',
    },
    {
      fixtureId: 'fixture-m18-partial-pattern',
      source: 'tests/m18/partial-pattern.js',
      expectedFault: 'outOfRange',
      reasonKey: 'interact.nothing-here',
      notes: 'The plan has only one step in it, so the push lands between pegs.',
    },
    {
      fixtureId: 'fixture-m18-runaway',
      source: 'tests/m18/runaway.js',
      expectedFault: 'runawayLoop',
      reasonKey: 'loop.budget-exceeded',
      notes: 'The walk-out loop is written before the pegs are pushed, so the gate never opens.',
    },
  ],
  accessibility: {
    keyboard: 'Arrow keys move and turn; Enter pushes a peg; Step mode advances one pattern at a time.',
    touch: 'Step mode has its own large button so each pattern can be watched on its own.',
    captions: 'Caption strip counts the pattern as "push 3 of 5" and names the peg.',
    textScale: 'Honors app textScale setting; briefing stays at 16px minimum.',
    reducedMotion: 'The wheel turn and the gate opening are instant under reduced motion.',
    screenReader: 'Each pushed peg is announced once, then the gate state when it changes.',
  },
  budgets: {
    maxCommands: 26,
    maxStepCount: 26,
    maxMissionObjects: 12,
    maxTriangles: 9000,
    estimatedActiveMinutes: 10,
  },
  rewards: [
    { rewardId: 'reward-lagoon-complete', assetId: 'asset.badge.lagoon', label: 'Lagoon Navigator', cosmetic: true },
  ],
};
