import type { MissionPackageSchema } from '@codequest/domain';

/**
 * The second debugging mission, and the off-by-one every programmer meets: four
 * lenses, a loop that runs three times. The starter is otherwise correct, so the
 * timeline shows three lit lenses and one dark one — the count is visible in the
 * world, not just in the code, and the fix is a single digit.
 */
export const m28FixTheLoop: MissionPackageSchema = {
  identity: {
    levelId: 'm28',
    zoneId: 'maker-observatory',
    apiVersion: 'v1',
    contentVersion: '2025.01',
    ordinal: 4,
    title: 'Fix the Loop',
    isCheckpoint: false,
    prerequisiteLevelIds: ['m27'],
  },
  zoneId: 'maker-observatory',
  curriculum: {
    primaryConcept: 'loopBoundary',
    newConcepts: ['offByOne'],
    priorConcepts: ['forLoop', 'loopBody', 'readTrace', 'moveForward', 'interact'],
    transferPrompt: 'How many times did the loop run, and how many times did it need to?',
  },
  startState: {
    avatar: { cellX: 0, cellZ: 0, facing: 'east' },
    collected: [],
    inventory: {},
    flags: {},
    stepCount: 0,
  },
  objects: [
    {
      id: 'spawn-1',
      label: 'Lens bench',
      required: false,
      kind: 'spawn',
      cell: { cellX: 0, cellZ: 0 },
      facing: 'east',
    },
    {
      id: 'lens-1',
      label: 'First lens',
      required: true,
      kind: 'interactable',
      cell: { cellX: 1, cellZ: 0 },
      actionKey: 'light',
      range: 1,
      initialState: 'dark',
      stateTransitions: [{ from: 'dark', to: 'lit' }],
    },
    {
      id: 'lens-2',
      label: 'Second lens',
      required: true,
      kind: 'interactable',
      cell: { cellX: 2, cellZ: 0 },
      actionKey: 'light',
      range: 1,
      initialState: 'dark',
      stateTransitions: [{ from: 'dark', to: 'lit' }],
    },
    {
      id: 'lens-3',
      label: 'Third lens',
      required: true,
      kind: 'interactable',
      cell: { cellX: 3, cellZ: 0 },
      actionKey: 'light',
      range: 1,
      initialState: 'dark',
      stateTransitions: [{ from: 'dark', to: 'lit' }],
    },
    {
      id: 'lens-4',
      label: 'Fourth lens',
      required: true,
      kind: 'interactable',
      cell: { cellX: 4, cellZ: 0 },
      actionKey: 'light',
      range: 1,
      initialState: 'dark',
      stateTransitions: [{ from: 'dark', to: 'lit' }],
    },
    {
      id: 'goal-1',
      label: 'Sky window',
      required: true,
      kind: 'goal',
      cell: { cellX: 5, cellZ: 0 },
      successConditions: ['avatarAtGoal'],
    },
    {
      id: 'bench-rail',
      label: 'Bench rail',
      required: false,
      kind: 'blocker',
      occupiedCells: [{ cellX: 6, cellZ: 0 }],
      reasonKey: 'rail.blocks',
    },
  ],
  allowedApi: [
    { capabilityId: 'cap-move-forward', unlockedFromMissionId: 'm01', apiVersion: 'v1' },
    { capabilityId: 'cap-interact', unlockedFromMissionId: 'm04', apiVersion: 'v1' },
  ],
  briefing: {
    storySentence: 'Four lenses must glow. The loop you were given lights only three.',
    goal: 'Fix the loop so all four lenses glow, then reach the sky window.',
    requiredCount: 5,
    optionalCount: 0,
    newConcepts: ['offByOne'],
    priorConcepts: ['forLoop', 'readTrace', 'moveForward', 'interact'],
    controls: ['move forward', 'interact'],
    checklist: ['Run the code first.', 'Count the lenses that glow.', 'Change the loop number.', 'Stop on the sky window.'],
    readAloud: 'Run it. Count the glowing lenses. One is missing.',
    locale: 'en-US',
  },
  starterCode:
    '// Four lenses need light. This loop stops too soon.\nfor (let i = 0; i < 3; i++) {\n  interact();\n  moveForward();\n}\n\nmoveForward();\n',
  hints: [
    {
      hintId: 'h1',
      stage: 1,
      prompt: 'Run the code. How many lenses glow at the end?',
      reveal: 'Three glow. One stays dark.',
    },
    {
      hintId: 'h2',
      stage: 2,
      prompt: 'Count the lenses in the room. Then find that number in the code.',
      reveal: 'There are four lenses, but the loop only says three.',
    },
    {
      hintId: 'h3',
      stage: 3,
      prompt: 'Change the number in the loop so it runs one more time.',
      scaffold: 'for (let i = 0; i < 4; i++) {',
    },
    {
      hintId: 'h4',
      stage: 4,
      prompt: 'Here is the answer.',
      reveal: 'for (let i = 0; i < 4; i++) {\n  interact();\n  moveForward();\n}\n\nmoveForward();',
    },
  ],
  analogousExample: {
    title: 'Four glasses',
    problem: 'You set the table for four. You only put out three glasses.',
    source: 'examples/four-glasses',
    note: 'Nothing else is wrong. You just count again and add the last one.',
  },
  completion: {
    stateInvariants: ['avatarAtGoal'],
    requiredObjectIds: ['goal-1', 'lens-1', 'lens-2', 'lens-3', 'lens-4'],
    requiredFlags: {
      'interactable.lens-1.state': true,
      'interactable.lens-2.state': true,
      'interactable.lens-3.state': true,
      'interactable.lens-4.state': true,
    },
    requiredCollected: [],
    terminalCell: { cellX: 5, cellZ: 0 },
    reflectionQuestion: 'How many times did the loop run, and how many times did it need to?',
  },
  conceptEvidence: [
    { ruleKey: 'rule.forLoop', kind: 'forLoop', threshold: 1 },
    {
      ruleKey: 'rule.sequence',
      expectedSequence: ['interact', 'moveForward', 'interact', 'moveForward', 'interact', 'moveForward', 'interact', 'moveForward'],
    },
  ],
  knownSolutions: [
    {
      solutionId: 'sol-m28-fixed-bound',
      source: 'demo/m28-fixed-bound.js',
      expectedCommandCount: 9,
      expectedStepCount: 9,
      notes: 'The loop bound moves from 3 to 4; the rest of the starter is untouched.',
    },
    {
      solutionId: 'sol-m28-expanded',
      source: 'demo/m28-expanded.js',
      expectedCommandCount: 9,
      expectedStepCount: 9,
      notes: 'The loop replaced by four written-out pairs; valid, and Step mode compares the two traces.',
    },
  ],
  expectedFailures: [
    {
      fixtureId: 'fixture-m28-unchanged-loop',
      source: 'tests/m28/unchanged-loop.js',
      expectedFault: 'blockedMove',
      reasonKey: 'goal-not-reached',
      notes: 'The starter runs as shipped: three lenses glow and the avatar stops short of the window.',
    },
    {
      fixtureId: 'fixture-m28-five-times',
      source: 'tests/m28/five-times.js',
      expectedFault: 'blockedMove',
      reasonKey: 'rail.blocks',
      notes: 'The loop is pushed to five, so the last light finds nothing and the last step hits the rail.',
    },
    {
      fixtureId: 'fixture-m28-swapped-body',
      source: 'tests/m28/swapped-body.js',
      expectedFault: 'outOfRange',
      reasonKey: 'interact.nothing-here',
      notes: 'The body steps before it lights, so lens one stays dark and the last light has no lens.',
    },
  ],
  accessibility: {
    keyboard: 'Step mode advances one loop turn at a time; Enter lights the lens in front.',
    touch: 'The loop counter has its own large readout beside the Step button.',
    captions: 'Caption strip counts "lens 3 of 4 lit" as each turn ends.',
    textScale: 'Honors app textScale setting; briefing stays at 16px minimum.',
    reducedMotion: 'Lenses switch to lit with no glow pulse under reduced motion.',
    screenReader: 'Announces the loop turn number and how many lenses are still dark.',
  },
  budgets: {
    maxCommands: 14,
    maxStepCount: 14,
    maxMissionObjects: 8,
    maxTriangles: 8000,
    estimatedActiveMinutes: 8,
  },
  rewards: [
    { rewardId: 'reward-lens-glow', assetId: 'asset.effect.lens-glow', label: 'Lens Glow', cosmetic: true },
  ],
};
