import type { MissionPackageSchema } from '@codequest/domain';

/**
 * The capstone. Every idea the game taught gets one job and no more: an array
 * of three power cells sets the loop count, a wind check picks the safe ramp,
 * one small function serves both consoles, and the last console opens the gate
 * to the beacon. The launch path is the longest arena in the zone, but each
 * stretch is a shape the child has already solved somewhere behind them.
 */
export const m30CodequestFinale: MissionPackageSchema = {
  identity: {
    levelId: 'm30',
    zoneId: 'maker-observatory',
    apiVersion: 'v2',
    contentVersion: '2025.01',
    ordinal: 6,
    title: 'CodeQuest Finale',
    isCheckpoint: true,
    prerequisiteLevelIds: ['m29'],
  },
  zoneId: 'maker-observatory',
  curriculum: {
    primaryConcept: 'capstone',
    newConcepts: [],
    priorConcepts: ['arrayLiteral', 'forLoop', 'functionDeclaration', 'conditional', 'predicate', 'collect', 'interact', 'planComments'],
    transferPrompt: 'Which idea from the whole game did your finale code lean on most?',
  },
  startState: {
    avatar: { cellX: 0, cellZ: 0, facing: 'east' },
    collected: [],
    inventory: {},
    flags: { 'world.windSafe': true },
    stepCount: 0,
  },
  objects: [
    {
      id: 'spawn-1',
      label: 'Launch floor',
      required: false,
      kind: 'spawn',
      cell: { cellX: 0, cellZ: 0 },
      facing: 'east',
    },
    {
      id: 'cell-1',
      label: 'First power cell',
      required: true,
      kind: 'collectible',
      cell: { cellX: 1, cellZ: 0 },
      collectionEffect: 'powerCell',
    },
    {
      id: 'cell-2',
      label: 'Second power cell',
      required: true,
      kind: 'collectible',
      cell: { cellX: 3, cellZ: 0 },
      collectionEffect: 'powerCell',
    },
    {
      id: 'cell-3',
      label: 'Third power cell',
      required: true,
      kind: 'collectible',
      cell: { cellX: 5, cellZ: 0 },
      collectionEffect: 'powerCell',
    },
    {
      id: 'storm-shutter',
      label: 'Storm shutter',
      required: false,
      kind: 'blocker',
      occupiedCells: [{ cellX: 6, cellZ: -1 }],
      reasonKey: 'storm.blocks',
    },
    {
      id: 'dome-wall',
      label: 'Dome wall',
      required: false,
      kind: 'blocker',
      occupiedCells: [{ cellX: 7, cellZ: 0 }],
      reasonKey: 'wall.blocks',
    },
    {
      id: 'console-1',
      label: 'First console',
      required: true,
      kind: 'interactable',
      cell: { cellX: 7, cellZ: 2 },
      actionKey: 'switch',
      range: 1,
      initialState: 'off',
      stateTransitions: [{ from: 'off', to: 'on' }],
    },
    {
      id: 'console-2',
      label: 'Second console',
      required: true,
      kind: 'interactable',
      cell: { cellX: 9, cellZ: 2 },
      actionKey: 'switch',
      range: 1,
      initialState: 'off',
      stateTransitions: [{ from: 'off', to: 'on' }],
    },
    {
      id: 'beacon-gate',
      label: 'Beacon gate',
      required: true,
      kind: 'blocker',
      occupiedCells: [{ cellX: 10, cellZ: 2 }],
      reasonKey: 'gate.closed',
      unlockedByFlag: 'interactable.console-2.state',
    },
    {
      id: 'goal-1',
      label: 'Star beacon',
      required: true,
      kind: 'goal',
      cell: { cellX: 11, cellZ: 2 },
      successConditions: ['avatarAtGoal'],
    },
    {
      id: 'launch-rail',
      label: 'Launch rail',
      required: false,
      kind: 'blocker',
      occupiedCells: [{ cellX: 12, cellZ: 2 }],
      reasonKey: 'rail.blocks',
    },
  ],
  allowedApi: [
    { capabilityId: 'cap-everything', unlockedFromMissionId: 'm06', apiVersion: 'v2' },
    { capabilityId: 'cap-sense-wind', unlockedFromMissionId: 'm19', apiVersion: 'v2' },
  ],
  briefing: {
    storySentence: 'This is the last climb. Three power cells, two consoles, one star beacon.',
    goal: 'Take all three cells, switch on both consoles, and reach the beacon.',
    requiredCount: 6,
    optionalCount: 0,
    newConcepts: [],
    priorConcepts: ['arrayLiteral', 'forLoop', 'functionDeclaration', 'conditional', 'collect', 'interact'],
    controls: ['move forward', 'turn left', 'turn right', 'collect', 'interact', 'check the wind'],
    checklist: ['Write your plan first.', 'Take all three power cells.', 'Check the wind, then turn.', 'Switch on both consoles.'],
    readAloud: 'Take the cells. Check the wind. Switch on both consoles. Reach the star.',
    locale: 'en-US',
  },
  starterCode:
    '// Your last mission. Write the plan first, in your own words.\nconst cells = ["one", "two", "three"];\n\n// 1. Take all three power cells.\n// 2. Check the wind, then turn the safe way.\n// 3. Switch on both consoles.\n// 4. Stop on the star beacon.\n',
  hints: [
    {
      hintId: 'h1',
      stage: 1,
      prompt: 'Walk to the first power cell by hand. What did that take?',
      reveal: 'Take a cell, then two steps. The next cell waits the same way.',
    },
    {
      hintId: 'h2',
      stage: 2,
      prompt: 'The list has three names. Let it count the cells for you.',
      scaffold: 'for (let i = 0; i < cells.length; i++) {\n  collect();\n  moveForward();\n  moveForward();\n}',
    },
    {
      hintId: 'h3',
      stage: 3,
      prompt: 'Ask the wind which way is safe. Then reuse one plan for both consoles.',
      scaffold:
        'if (isWindSafe()) {\n  turnRight();\n} else {\n  turnLeft();\n}\n\nfunction useConsole() {\n  interact();\n  moveForward();\n  moveForward();\n}',
    },
    {
      hintId: 'h4',
      stage: 4,
      prompt: 'Here is the answer.',
      reveal:
        'const cells = ["one", "two", "three"];\n\nfor (let i = 0; i < cells.length; i++) {\n  collect();\n  moveForward();\n  moveForward();\n}\n\nif (isWindSafe()) {\n  turnRight();\n} else {\n  turnLeft();\n}\n\nmoveForward();\nmoveForward();\nturnLeft();\n\nfunction useConsole() {\n  interact();\n  moveForward();\n  moveForward();\n}\n\nuseConsole();\nuseConsole();\nmoveForward();',
    },
  ],
  analogousExample: {
    title: 'The big show',
    problem: 'You put on a show. You use every trick you have learned this year.',
    source: 'examples/the-big-show',
    note: 'Nothing new tonight. Old tricks, in the right order, on the biggest stage.',
  },
  completion: {
    stateInvariants: ['avatarAtGoal'],
    requiredObjectIds: ['goal-1', 'cell-1', 'cell-2', 'cell-3', 'console-1', 'console-2', 'beacon-gate'],
    requiredFlags: {
      'interactable.console-1.state': true,
      'interactable.console-2.state': true,
    },
    requiredCollected: ['cell-1', 'cell-2', 'cell-3'],
    terminalCell: { cellX: 11, cellZ: 2 },
    reflectionQuestion: 'Which idea helped you most: the list, the loop, the plan, or the check?',
  },
  conceptEvidence: [
    { ruleKey: 'rule.arrayIndexed', kind: 'arrayIndexed', threshold: 1 },
    { ruleKey: 'rule.forLoop', kind: 'forLoop', threshold: 1 },
    { ruleKey: 'rule.conditionalBranch', kind: 'conditionalBranch', threshold: 1 },
    { ruleKey: 'rule.functionDeclared', kind: 'functionDeclared', threshold: 1 },
    {
      ruleKey: 'rule.sequence',
      expectedSequence: ['collect', 'moveForward', 'moveForward', 'collect', 'moveForward', 'moveForward', 'collect'],
    },
  ],
  knownSolutions: [
    {
      solutionId: 'sol-m30-full-toolkit',
      source: 'demo/m30-full-toolkit.js',
      expectedCommandCount: 20,
      expectedStepCount: 20,
      notes: 'Array loop for the cells, wind check for the ramp, useConsole() twice, one last step to the beacon.',
    },
    {
      solutionId: 'sol-m30-written-out',
      source: 'demo/m30-written-out.js',
      expectedCommandCount: 20,
      expectedStepCount: 20,
      notes: 'The same twenty commands with no loop or function; accepted, and the recap shows what the tools saved.',
    },
  ],
  expectedFailures: [
    {
      fixtureId: 'fixture-m30-missing-cell',
      source: 'tests/m30/missing-cell.js',
      expectedFault: 'blockedMove',
      reasonKey: 'goal-not-reached',
      notes: 'The loop runs twice, so the third power cell is left on the floor.',
    },
    {
      fixtureId: 'fixture-m30-one-console',
      source: 'tests/m30/one-console.js',
      expectedFault: 'closedGate',
      reasonKey: 'gate.closed',
      notes: 'Only the first console is switched on, so the beacon gate never opens.',
    },
    {
      fixtureId: 'fixture-m30-ignores-wind',
      source: 'tests/m30/ignores-wind.js',
      expectedFault: 'blockedMove',
      reasonKey: 'storm.blocks',
      notes: 'The wind check is skipped and the route turns left into the closed storm shutter.',
    },
    {
      fixtureId: 'fixture-m30-runaway',
      source: 'tests/m30/runaway.js',
      expectedFault: 'timeout',
      reasonKey: 'loop.budget-exceeded',
      notes: 'A while loop waits on a console that is never switched on, so the run hits the time budget.',
    },
  ],
  accessibility: {
    keyboard: 'Arrow keys move and turn; Enter switches a console; Step mode walks the plan one line at a time.',
    touch: 'Plan cards, array viewer, and the wind readout each have their own large tap target.',
    captions: 'Caption strip tracks cells held, consoles on, and the wind state as they change.',
    textScale: 'Honors app textScale setting; briefing stays at 16px minimum.',
    reducedMotion: 'The launch, the gate, and the beacon light are instant under reduced motion.',
    screenReader: 'Announces each objective as it completes and reads the end-of-game recap in order.',
  },
  budgets: {
    maxCommands: 30,
    maxStepCount: 30,
    maxMissionObjects: 14,
    maxTriangles: 10000,
    estimatedActiveMinutes: 15,
  },
  rewards: [
    { rewardId: 'reward-finale-badge', assetId: 'asset.badge.codequest-finale', label: 'CodeQuest Maker', cosmetic: true },
    { rewardId: 'reward-star-cloak', assetId: 'asset.gear.star-cloak', label: 'Star Cloak', cosmetic: true },
  ],
};
